CREATE TABLE BORROW
(
	LOANNO INT,
	CNAME VARCHAR(50),
	BNAME VARCHAR(50),
	AMOUNT DECIMAL(8,2)
)

INSERT INTO BORROW(LOANNO,CNAME,BNAME,AMOUNT)
VALUES
(201,'ANIL','VRCE',1000)
INSERT INTO BORROW(LOANNO,CNAME,BNAME,AMOUNT)
VALUES
(206,'MEHUL','AJNI',5000)
INSERT INTO BORROW(LOANNO,CNAME,BNAME,AMOUNT)
VALUES
(311,'SUNIL','DHARAMPETH',3000)
INSERT INTO BORROW(LOANNO,CNAME,BNAME,AMOUNT)
VALUES
(321,'MADHURI','ANDHERI',2000)
INSERT INTO BORROW(LOANNO,CNAME,BNAME,AMOUNT)
VALUES
(375,'PRAMOD','VIHAR',8000)
INSERT INTO BORROW(LOANNO,CNAME,BNAME,AMOUNT)
VALUES
(481,'KRANTI','NEHRU PALACE',3000)