CREATE TABLE CUSTOMERS
(
	CNAME VARCHAR(50),
	CITY VARCHAR(50)
)

INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('ANIL','CALCUTTA')
INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('SUNIL','DELHI')
INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('MEHUL','BARODA')
INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('MANDAR','PATNA')
INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('MADHURI','NAGPUR')
INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('PRAMOD','NAGPUR')
INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('SANDIP','SURAT')
INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('SHIVANI','BOMBAY')
INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('KRANTI','BOMBAY')
INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES
('NAREN','BOMBAY')