USE CSE_B_312
--LAB = B

--1
SELECT TOP 5 * FROM DEPOSIT

--2
SELECT TOP 3 * FROM DEPOSIT WHERE AMOUNT > 1000

--3
SELECT TOP 5 LOANNO, CNAME FROM BORROW WHERE BNAME<>'ANDHERI'

--4
SELECT DISTINCT CITY FROM CUSTOMERS 

--5
SELECT DISTINCT BNAME FROM BRANCH